namespace Soundtrail.Services.Enrichment.Shared.Orchestration;

public sealed record HighPriorityVerifyYouTubeMusicPlaybackReferenceCommandMessage(VerifyYouTubeMusicPlaybackReferenceCommand Command);
