namespace Soundtrail.Services.Enrichment.Shared.Orchestration;

public sealed record LowPriorityResolveYouTubeMusicPlaybackReferenceCommandMessage(ResolveYouTubeMusicPlaybackReferenceCommand Command);
